---
title:"Exploratory and hypothesis testing analysis"
output: rmarkdown::github_document
author: Muhammad
---

# import data
```{r}
PE_microplastic <- read_excel(file.choose(), sheet = "PE_abu")
```

```{r Table of microplastic only}
#s
PE_microplastic
```

```{r}

#subet the variables: Age_maturity, Genotype & Treatment

Age<- PE_microplastic[,'Age_maturity']

Genotype <- PE_microplastic[,'Genotype']

Treatment<- PE_microplastic[,'Treatment']
```

```{r}
 #Do the anova for Age_maturity:

PE_Age_ano <- lmer(Age_maturity ~ Treatment*Genotype + (1|Genotype:Replicates), data = PE_microplastic)

```

```{r}

anova(PE_Age_ano)
```

```{r}

#Plot the histogram of the residuals

x=residuals(PE_Age_ano)
plotNormalHistogram(x)
```

```{r}

#run anova for a log transform Age_maturity data:

PE_Age_log_ano <- lmer(log(Age_maturity) ~ Treatment*Genotype + (1|Genotype:Replicates), data = PE_microplastic)
```

```{r}

anova(PE_Age_log_ano)
```

```{r}
log_age_PE = residuals(PE_Age_log_ano)
plotNormalHistogram(log_age_PE)

```



```{r}
#plot the Q-Q plot:

qqnorm(residuals(PE_Age_ano),
       ylab = 'Sample Quantiles for residuals')

qqline(residuals(PE_Age_ano),
       col='red')
```


```{r}
qqnorm(residuals(PE_Age_log_ano),
       ylab = 'Sample Quantiles for residuals')

qqline(residuals(PE_Age_log_ano),
       col='red')

```

```{r}
# PCA:only works with quantitative variables

colSums(is.na(PE_microplastic))

```

```{r}
#PCA
colSums(is.na(PE_microplastic))

```

```{r}
PE_microplastic$Genotype <- factor(PE_microplastic$Genotype, levels = c("LRV_0_1", "LR2_36_1"))

```

```{r}

PE_microplastic
```

```{r}

PE <- PE_microplastic[-c(1,5,7,8,9:10)]

```

```{r}
PE <- PE[complete.cases(PE),]

```


```{r}
PE

```


```{r}

PE[3:5]<- log(PE[3:5]+0.5)
```

```{r}
logPE_data <- PE[,c(3:5)]

```

```{r}
logPE_data_pca <- prcomp(logPE_data, scale. = TRUE)

```


```{r}
logPE_data_pca


```



```{r}

summary(logPE_data_pca)

```


```{r}

Genotype <- as.factor(PE_microplastic$Genotype)
```

```{r}
fviz_pca_biplot(logPE_data_pca,
             col.ind = Genotype,
              palette = c("LRV_0_1"="red","LR2_36_1"="black"),
             addEllipses = TRUE, 
             col.var="blue",
             arrowsize=0.2,
             labelsize=3,
             geom.ind = "point",
             pointsize=1,
             pointshape=19,
             mean.point=F,
             xlim=c(-5,5),
             ylim=c(-3,3),
             var.scale=0.5,
             ellipse.type = "confidence",
             legend.title = "Genotype",
             repel = TRUE,
             )


```

```{r figure-setup}

fviz_pca_biplot(logPE_data_pca)

```

```{r}

fviz_pca_biplot(logPE_data_pca, label="var", habillage=PE_microplastic$Genotype,
               addEllipses=TRUE, ellipse.level=0.95)

```
```{r}
X <- readRDS(system.file("testdata", "three-pops.rds", package = "bigutilsr"))

```

```{r}

#pca <- prcomp(X, scale. = TRUE, rank. = 10)

logPE_data_PCa<- prcomp(logPE_data, scale. = TRUE, rank. = 10)

#U <- pca$x
#library(ggplot2)
#theme_set(bigstatsr::theme_bigstatsr(0.8))
#qplot(U[, 1], U[, 2]) + coord_equal()
```



```{r}
U <- logPE_data_PCa$x

```


```{r}
library(ggplot2)

```


```{r}
theme_set(bigstatsr::theme_bigstatsr(0.8))

```

```{r}
qplot(U[, 1], U[, 2]) + coord_equal()

```
```{r}
#Measuring Outliers
apply(U, 2, function(x) which( abs(x - mean(x)) > (3 * sd(x)) ))
## integer(0)

```
```{r}
apply(U, 2, function(x) which( abs(x - mean(x)) > (3 * sd(x)) ))
## integer(0)

```
```{r}
library(magrittr)

```

```{r}
apply(U, 2, function(x) which( abs(x - mean(x)) > (3 * sd(x)) )) %>%
  Reduce(union, .)
#[1] 1

```

```{r}
#A more robust variation

ind.out <- apply(U, 2, function(x) which( (abs(x - median(x)) / mad(x)) > 6 )) %>%
  Reduce(union, .) %>%
  print()
## [1]   1 516

```
 
 we get an outlier
 
 
```{r}
col <- rep("black", nrow(U)); col[ind.out] <- "red"
qplot(U[, 1], U[, 3], color = I(col), size = I(2)) + coord_equal()

#explain

```

```{r}
dist <- apply(U, 2, function(x) abs(x - median(x)) / mad(x)) %>%
  apply(1, max)
qplot(U[, 1], U[, 3], color = dist, size = I(3)) + coord_equal() + 
  scale_color_viridis_c(trans = "log", breaks = c(1, 3, 6))


```
```{r}

qplot(y = sort(dist, decreasing = TRUE)) +
  geom_hline(yintercept = 6, color = "red")
```
```{r}
#Using robust Mahalanobi's distance

dist2 <- covRob(U, estim = "pairwiseGK")$dist
qplot(dist, sqrt(dist2))

```
```{r}

cowplot::plot_grid(
  qplot(U[, 1], U[, 2], color = dist2, size = I(2)) + coord_equal() + 
    scale_color_viridis_c(trans = "log", breaks = NULL),
  qplot(U[, 3], U[, 3], color = dist2, size = I(2)) + coord_equal() + 
    scale_color_viridis_c(trans = "log", breaks = NULL),
  rel_widths = c(0.7, 0.4), scale = 0.95
)
```


```{r}

pval <- pchisq(dist2, df = 10, lower.tail = FALSE)
hist(pval)

```

```{r}

is.out <- (pval < (0.05 / length(dist2)))  # Bonferroni correction
sum(is.out)
## [1] 33
qplot(U[, 3], U[, 3], color = is.out, size = I(3)) + coord_equal()

```

```{r}
#Tukey's rule
x <- rnorm(PE_microplastic)
(tukey_up  <- quantile(x, 0.75) + 1.5 * IQR(x))
##     75% 
## 3.7635
(tukey_low <- quantile(x, 0.25) - 1.5 * IQR(x))
##       25% 
## 2.70692
hist(x); abline(v = c(tukey_low, tukey_up), col = "red")

```

```{r}

mean(x < tukey_low | x > tukey_up)
## [1] 0.0057
```

```{r}
x <- rchisq(PE_microplastic, df = 5)
(tukey_up  <- quantile(x, 0.75) + 1.5 * IQR(x))
##      75% 
## 12.97454
(tukey_low <- quantile(x, 0.25) - 1.5 * IQR(x))
##       25% 
## -3.534011

hist(x, "FD"); abline(v = c(tukey_low, tukey_up), col = "red")

```
```{r}

mean(x < tukey_low | x > tukey_up)
## [1] 0.090909
```
```{r}

x <- rchisq(PE_microplastic, df = 5)
(tukey_up  <- quantile(x, 0.75) + 1.5 * IQR(x))
##      75% 
## 36.76838
hist(x, "FD"); abline(v = tukey_up, col = "red")
abline(v = print(tukey_mc_up(x, coef = 1.5)), col = "blue")
## [1]35.35445 
abline(v = print(tukey_mc_up(x)), col = "green")  # accounts for multiple testing
```
```{r}
#Histogram gap

hist(dist, breaks = nclass.scottRob)
str(hist_out(dist))
## List of 2
##  $ x  : num [1:13] 1.28 0.8 1.61 1.1 3.66 ...
##  $ lim: num [1:2] -Inf 4.5
abline(v = hist_out(dist)$lim[2], col = "red")


```

```{r}

hist(dist2, breaks = nclass.scottRob)
abline(v = hist_out(dist2)$lim[2], col = "red")
```
this does not assume any normality in the distribution of the data and its compact.

```{r}


```

```{r}

#import PFOS_PFOA data
PFOS_PFOA_abu <- read_excel(file.choose(), sheet = "PFOS_PFOA_abu")

```


```{r}
PFOS_PFOA_abu

```
```{r}

colSums(is.na(PFOS_PFOA_abu))

```


```{r}
PFOS_PFOA_abu$Genotype <- factor(PFOS_PFOA_abu$Genotype, levels = c("LRV_0_1", "LR2_36_1"))

```


```{r}
Abu_PFOS_PFOA <- PFOS_PFOA_abu[-c(1,5,7,8,9:10)]

```


```{r}
Abu_PFOS_PFOA

```


```{r}

Abu_PFOS_PFOA[3:5]<- log(Abu_PFOS_PFOA[3:5]+0.5)

```


```{r}
logAb_PFOS_PFOA <- Abu_PFOS_PFOA[,c(3:5)]

```

```{r}

logAb_PFOS_PFOA_pca <- prcomp(logAb_PFOS_PFOA, scale. = TRUE)

```


```{r}
logAb_PFOS_PFOA_pca

```


```{r}
summary(logAb_PFOS_PFOA_pca)

```

```{r}

Genotype <- as.factor(PFOS_PFOA_abu$Genotype)
```


```{r}
fviz_pca_biplot(logAb_PFOS_PFOA_pca,
             col.ind = Genotype,
              palette = c("LRV_0_1"="red","LR2_36_1"="black"),
             addEllipses = TRUE, 
             col.var="blue",
             arrowsize=0.2,
             labelsize=3,
             geom.ind = "point",
             pointsize=1,
             pointshape=19,
             mean.point=F,
             xlim=c(-5,5),
             ylim=c(-3,3),
             var.scale=0.5,
             ellipse.type = "confidence",
             legend.title = "Genotype",
             repel = TRUE,
             )



```


```{r}
#import PFOS data

PFOS <- read_excel(file.choose(), sheet = "PFOS_abu")


```



