---
title: "Exploratory and hypothesis testing analysis"
output: rmarkdown::github_document
author: Muhammad
---

#load libraries
```{r}
library(readxl)
```


# import data
```{r}
MP_Data <- read_excel(file.choose(), sheet = 'MP')

```

```{r}
MP_Data
```
```{r}
#subet the variables: Age_maturity, Genotype & Treatment

Age<- MP_Data[,'Age_maturity']

Genotype <-MP_Data[,'Genotypes']

Treatment<-MP_Data[,'Treatment']

```

```{r}
install.packages("rms")

```



```{r}
#load packages

library(lmerTest) # loads p-values for type I,II,III anova.
library(rcompanion) # provides summary of analysis of a dataset.
library(heplots) # loads HE plots for visualizing hypothesis test.

```


```{r}
# Do the anova for Age_maturity:

Age_ano <- lmer(Age_maturity ~ Treatment*Genotypes + (1|Genotypes:Replicates), data = MP_Data)


```

```{r}
anova(Age_ano)

```

```{r}
#Plot the histogram of the residuals

x=residuals(Age_ano)
plotNormalHistogram(x)

```

```{r}

#run anova for a log transform Age_maturity data:

Age_log_ano <- lmer(log(Age_maturity) ~ Treatment*Genotypes + (1|Genotypes:Replicates), data = MP_Data)

```

```{r}
anova(Age_log_ano)
```

```{r}
log_age = residuals(Age_log_ano)
plotNormalHistogram(log_age)
```

```{r}
#plot the Q-Q plot:

qqnorm(residuals(Age_ano),
       ylab = 'Sample Quantiles for residuals')

qqline(residuals(Age_ano),
       col='red')

```
```{r}
qqnorm(residuals(Age_log_ano),
       ylab = 'Sample Quantiles for residuals')

qqline(residuals(Age_log_ano),
       col='red')


```
```{r}
#PCA: analysis of quantitative variables only

colSums(is.na(MP_Data))

```
```{r}

str(MP_Data)
```

```{r}

MP_Data$Genotypes <- factor(MP_Data$Genotypes, levels = c("LRV-0-1", "LR2-36-01"))

```


```{r}
MP_Data

```
```{r}
TY <- MP_Data[-c(1,5:6,8:9)]

```


```{r}
TY
```
```{r}
TY <- TY[complete.cases(TY),]

```

```{r}

TY
```

```{r}
TY[3:5]<- log(TY[3:5]+0.5)

```


```{r}
logTY_data <- TY[,c(3:5)]

```

```{r}
logTY_data

```


```{r}
logTY_data_pca <- prcomp(logTY_data, scale. = TRUE)

```

```{r}
logTY_data_pca
```



```{r}

summary(logTY_data_pca)
```

```{r}
library(FactoMineR)
library(devtools)
```

```{r}
install_github("kassambara/factoextra")

```
```{r}
library(factoextra)
```

```{r}
Genotypes <- as.factor(MP_Data$Genotypes)


fviz_pca_biplot(logTY_data_pca,
             col.ind = Genotypes,
              palette = c("LRV-0-1"="red","LR2-36-01"="black"),
             addEllipses = TRUE, 
             col.var="blue",
             arrowsize=0.2,
             labelsize=3,
             geom.ind = "point",
             pointsize=1,
             pointshape=19,
             mean.point=F,
             xlim=c(-5,5),
             ylim=c(-3,3),
             var.scale=0.5,
             ellipse.type = "confidence",
             legend.title = "Genotype",
             repel = TRUE,
             )

```


```{r}
#import MP_PFOA data
MP_PFOA_T <- read_excel(file.choose(), sheet = "MP_PFOA_Tia")

```



```{r}
MP_PFOA_T


```

```{r}
colSums(is.na(MP_PFOA_T))

```


```{r}

MP_PFOA_T$Genotypes <- factor(MP_PFOA_T$Genotypes, levels = c("LRV-0-1", "LR2-36-01"))


```


```{r}
MP_PFOA_T


```
```{r}
Ta <- MP_PFOA_T[-c(1,5:6,8:9)]

```


```{r}
Ta
```


```{r}

Ta <- Ta[complete.cases(Ta),]
```




```{r}
Ta
```


```{r}


Ta[3:5]<- log(Ta[3:5]+0.5)

```



```{r}
logTa_data <- Ta[,c(3:5)]

```


```{r}
logTa_data_pca <- prcomp(logTa_data, scale. = TRUE)

```


```{r}
logTa_data_pca

```


```{r}

summary(logTa_data_pca)
```


```{r}

Genotypes <- as.factor(MP_PFOA_T$Genotypes)
```


```{r}

fviz_pca_biplot(logTa_data_pca,
             col.ind = Genotypes,
              palette = c("LRV-0-1"="red","LR2-36-01"="black"),
             addEllipses = TRUE, 
             col.var="blue",
             arrowsize=0.2,
             labelsize=3,
             geom.ind = "point",
             pointsize=1,
             pointshape=19,
             mean.point=F,
             xlim=c(-5,5),
             ylim=c(-3,3),
             var.scale=0.5,
             ellipse.type = "confidence",
             legend.title = "Genotype",
             repel = TRUE,
             )


```

```{r}
#import MP+PFOS+PFOA data

MP_PFOS_PFOA <- read_excel(file.choose(), sheet = "MP+PFOS+PFOA_Tia")

```

```{r}
colSums(is.na(MP_PFOS_PFOA))

```


```{r}


str(MP_PFOS_PFOA)
```
```{r}
MP_PFOS_PFOA$Genotypes <- factor(MP_PFOS_PFOA$Genotypes, levels = c("LRV-0-1", "LR2-36-01"))

```


```{r}
MP_PF_PA <- MP_PFOS_PFOA[-c(1,5:6,8:9)]

```

```{r}

MP_PF_PA
```


```{r}

MP_PF_PA[3:5]<- log(MP_PF_PA[3:5]+0.5)
```


```{r}



```